<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <meta name="generator" content="GNU make coupled with GNU awk to parse templates. Markdown to parse contents." />
  <meta http-equiv="content-type" content="text/html; charset=utf-8" />
  <meta name="author" content="Clément David" />
  <meta name="keywords" content="davidcl, clement, david, c.david86" />
  <meta name="description" content="Clément David's CV, articles and all official stuff." />
  <meta name="robots" content="all" />

  <title>GnuBasedWebGeneration: Makefile</title>
  <meta name="keywords" content="make, Makefile, template" />
  <link rel="stylesheet" type="text/css" href="/davidcl/styles/light.css" media="all" />
  <link rel="stylesheet" type="text/css" href="/davidcl/styles/print.css" media="print" />
  <link rel="stylesheet" type="text/css" href="/davidcl/styles/default.css" media="screen" />
  <link rel="stylesheet" type="text/css" href="/davidcl/styles/highlight.css" />
  
  
  <link rel="Shortcut Icon" type="image/x-icon" href="/davidcl/img/favicon.ico" />
</head>

<body>
  <div id="nonFooter">
    <div id="header"> <div id="banner"></div> <p><a href="/davidcl/index.xhtml">davidcl</a> > <a href="/davidcl/articles/index.xhtml">articles</a> > <a href="/davidcl/articles/GnuBasedWebGeneration/index.xhtml">GnuBasedWebGeneration</a> > Makefile</p> </div>
    <div id="toc"></div>
    <div id="contents"> <pre class="hl"><span class="hl slc">#</span>
<span class="hl slc"># This Makefile is part of Clément David's homepage.</span>
<span class="hl slc">#</span>
<span class="hl slc"># It will generate html files from text (xhtml or markdown) and templates.</span>
<span class="hl slc">#</span>

<span class="hl slc"># Tools path</span>
MARKDOWN <span class="hl sym">= /</span>usr<span class="hl sym">/</span>bin<span class="hl sym">/</span>markdown
AWK <span class="hl sym">= /</span>usr<span class="hl sym">/</span>bin<span class="hl sym">/</span>gawk
SH <span class="hl sym">= /</span>bin<span class="hl sym">/</span>sh
RM <span class="hl sym">= /</span>bin<span class="hl sym">/</span><span class="hl kwa">rm</span> <span class="hl sym">-</span>f
CAT <span class="hl sym">= /</span>bin<span class="hl sym">/</span>cat
TOUCH <span class="hl sym">= /</span>bin<span class="hl sym">/</span>touch

<span class="hl slc"># Setting default searching directories</span>
directories <span class="hl sym">=</span> projects articles about

<span class="hl slc"># including per-directory specific rules (if any).</span>
<span class="hl slc"># Use to add sub-directories to the $(directories) variables</span>
<span class="hl sym">-</span><span class="hl kwb">include</span> <span class="hl sym">$(</span><span class="hl kwa">addsuffix</span> <span class="hl sym">/</span>Makefile<span class="hl sym">, $(</span>directories<span class="hl sym">))</span>

<span class="hl slc"># Adding others path to the directories variable after inclusion</span>
directories <span class="hl sym">+=</span> . styles

<span class="hl slc"># Setting helpers variables</span>
text-files <span class="hl sym">= $(</span><span class="hl kwa">wildcard</span> <span class="hl sym">$(</span><span class="hl kwa">addsuffix</span> <span class="hl sym">/*</span>.text<span class="hl sym">, $(</span>directories<span class="hl sym">)))</span>
html-files <span class="hl sym">= $(</span><span class="hl kwa">wildcard</span> <span class="hl sym">$(</span><span class="hl kwa">addsuffix</span> <span class="hl sym">/*</span>.html<span class="hl sym">, $(</span>directories<span class="hl sym">)))</span>

img-files <span class="hl sym">= $(</span><span class="hl kwa">wildcard</span> <span class="hl sym">$(</span><span class="hl kwa">addsuffix</span> <span class="hl sym">/*</span>.png<span class="hl sym">, $(</span>directories<span class="hl sym">)))</span> \
		<span class="hl sym">$(</span><span class="hl kwa">wildcard</span> <span class="hl sym">$(</span><span class="hl kwa">addsuffix</span> <span class="hl sym">/*</span>.jpg<span class="hl sym">, $(</span>directories<span class="hl sym">)))</span> \
		<span class="hl sym">$(</span><span class="hl kwa">wildcard</span> <span class="hl sym">$(</span><span class="hl kwa">addsuffix</span> <span class="hl sym">/*</span>.svg<span class="hl sym">, $(</span>directories<span class="hl sym">)))</span>
other-files <span class="hl sym">= $(</span><span class="hl kwa">wildcard</span> <span class="hl sym">$(</span><span class="hl kwa">addsuffix</span> <span class="hl sym">/*</span>.ico<span class="hl sym">, $(</span>directories<span class="hl sym">)))</span> \
		<span class="hl sym">$(</span><span class="hl kwa">wildcard</span> <span class="hl sym">$(</span><span class="hl kwa">addsuffix</span> <span class="hl sym">/*</span>.css<span class="hl sym">, $(</span>directories<span class="hl sym">)))</span>

all-xhtml <span class="hl sym">= $(</span>text-files<span class="hl sym">:%</span>.text<span class="hl sym">=%</span>.xhtml<span class="hl sym">) $(</span>html-files<span class="hl sym">:%</span>.html<span class="hl sym">=%</span>.xhtml<span class="hl sym">)</span>
all-atom <span class="hl sym">= $(</span>text-files<span class="hl sym">:%</span>.text<span class="hl sym">=%</span>.atom<span class="hl sym">) $(</span>html-files<span class="hl sym">:%</span>.html<span class="hl sym">=%</span>.atom<span class="hl sym">)</span>

<span class="hl slc"># Commands</span>
default<span class="hl sym">:</span>
	&#64;echo <span class="hl str">&quot;No default rule, try:&quot;</span>
	&#64;echo <span class="hl str">&quot;  make all       # do almost everything&quot;</span>
	&#64;echo <span class="hl str">&quot;  make site      # generate html from written files&quot;</span>
	&#64;echo <span class="hl str">&quot;  make feed      # generate Atom feed from xhtml files&quot;</span>
	&#64;echo <span class="hl str">&quot;  make update    # will connect to the FTP server and updating change.&quot;</span>
	&#64;echo <span class="hl str">&quot;  make clean     # remove generated files&quot;</span>

<span class="hl kwa">all</span><span class="hl sym">:</span> site update

site<span class="hl sym">: $(</span>all-xhtml<span class="hl sym">)</span>

feed<span class="hl sym">: $(</span>all-atom<span class="hl sym">)</span>
	&#64;echo <span class="hl str">&quot;feed is not implemented by now&quot;</span> <span class="hl sym">&gt; /</span>dev<span class="hl sym">/</span>stderr

update<span class="hl sym">: $(</span>all-xhtml<span class="hl sym">) $(</span>img-files<span class="hl sym">) $(</span>other-files<span class="hl sym">)</span>
	<span class="hl sym">$(</span>SH<span class="hl sym">)</span> .<span class="hl sym">/</span>update.sh <span class="hl sym">$</span>?
	<span class="hl sym">$(</span>TOUCH<span class="hl sym">)</span> update

.PHONY<span class="hl sym">:</span> <span class="hl kwa">clean</span>
<span class="hl kwa">clean</span><span class="hl sym">:</span>
	<span class="hl sym">$(</span>RM<span class="hl sym">) $(</span>text-files<span class="hl sym">:%</span>.text<span class="hl sym">=%</span>.html<span class="hl sym">)</span>
	<span class="hl sym">$(</span>RM<span class="hl sym">) $(</span>all-xhtml<span class="hl sym">)</span>
	<span class="hl sym">$(</span>RM<span class="hl sym">) $(</span>all-atom<span class="hl sym">)</span>
	<span class="hl sym">$(</span>RM<span class="hl sym">)</span> update

<span class="hl slc"># Generic rules</span>
<span class="hl sym">%</span>.html<span class="hl sym">: %</span>.text
	<span class="hl sym">$(</span>MARKDOWN<span class="hl sym">) $&lt; &gt; $</span>&#64;

<span class="hl sym">%</span>.xhtml<span class="hl sym">: %</span>.html templates<span class="hl sym">/</span>default.template template.awk
	<span class="hl sym">$(</span>AWK<span class="hl sym">) -</span>f template.awk <span class="hl sym">-</span>v input<span class="hl sym">=</span><span class="hl str">&quot;$&lt;&quot;</span> <span class="hl sym">-</span>v output<span class="hl sym">=</span><span class="hl str">&quot;$&#64;&quot;</span> templates<span class="hl sym">/</span>default.template

<span class="hl sym">%</span>.atom<span class="hl sym">: %</span>.html templates<span class="hl sym">/</span>atom-entry.template template.awk
	<span class="hl sym">$(</span>AWK<span class="hl sym">) -</span>f template.awk <span class="hl sym">-</span>v input<span class="hl sym">=</span><span class="hl str">&quot;$&lt;&quot;</span> <span class="hl sym">-</span>v output<span class="hl sym">=</span><span class="hl str">&quot;$&#64;&quot;</span> templates<span class="hl sym">/</span>atom-entry.template

</pre>
<!--HTML generated by highlight 2.7, http://www.andre-simon.de/-->
 </div>
  </div>

  <div id="footer">
    <p>© 2009+ Clément David - All texts and images can be used
    with respect to the <a href=
    "http://www.opensource.org/licenses/artistic-license-2.0.php">Artistic
    license 2.0</a>.<br /> Generated on 2010-01-10T22:46:08+01:00. 
    <a href="http://validator.w3.org/check/referer" title="Check the validity of this site&#8217;s XHTML">xhtml</a>
    <a href="http://jigsaw.w3.org/css-validator/check/referer" title="Check the validity of this site&#8217;s CSS">css</a>
    <a href="/davidcl/sitemap.xhtml" title="Sitemap of this site">sitemap</a> &nbsp;</p>
  </div>
</body>
</html>

