<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"  "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>Makefile.make</title>
<link rel="stylesheet" type="text/css" href="/davidcl/styles/highlight.css"/>
</head>
<body class="hl"><pre class="hl"><span class="hl slc">#</span>
<span class="hl slc"># This Makefile is part of Clément David's homepage.</span>
<span class="hl slc">#</span>
<span class="hl slc"># It will generate html files from text (xhtml or markdown) and templates.</span>
<span class="hl slc">#</span>

<span class="hl slc"># Tools path</span>
MARKDOWN <span class="hl sym">= /</span>usr<span class="hl sym">/</span>bin<span class="hl sym">/</span>markdown
AWK <span class="hl sym">= /</span>usr<span class="hl sym">/</span>bin<span class="hl sym">/</span>gawk
SH <span class="hl sym">= /</span>bin<span class="hl sym">/</span>sh
RM <span class="hl sym">= /</span>bin<span class="hl sym">/</span><span class="hl kwa">rm</span> <span class="hl sym">-</span>f
CAT <span class="hl sym">= /</span>bin<span class="hl sym">/</span>cat
TOUCH <span class="hl sym">= /</span>bin<span class="hl sym">/</span>touch

<span class="hl slc"># Setting default searching directories</span>
directories <span class="hl sym">=</span> projects articles about

<span class="hl slc"># including per-directory specific rules (if any).</span>
<span class="hl slc"># Use to add sub-directories to the $(directories) variables</span>
<span class="hl sym">-</span><span class="hl kwb">include</span> <span class="hl sym">$(</span><span class="hl kwa">addsuffix</span> <span class="hl sym">/</span>Makefile<span class="hl sym">, $(</span>directories<span class="hl sym">))</span>

<span class="hl slc"># Adding others path to the directories variable after inclusion</span>
directories <span class="hl sym">+=</span> . styles

<span class="hl slc"># Setting helpers variables</span>
text-files <span class="hl sym">= $(</span><span class="hl kwa">wildcard</span> <span class="hl sym">$(</span><span class="hl kwa">addsuffix</span> <span class="hl sym">/*</span>.text<span class="hl sym">, $(</span>directories<span class="hl sym">)))</span>
html-files <span class="hl sym">= $(</span><span class="hl kwa">wildcard</span> <span class="hl sym">$(</span><span class="hl kwa">addsuffix</span> <span class="hl sym">/*</span>.html<span class="hl sym">, $(</span>directories<span class="hl sym">)))</span>

img-files <span class="hl sym">= $(</span><span class="hl kwa">wildcard</span> <span class="hl sym">$(</span><span class="hl kwa">addsuffix</span> <span class="hl sym">/*</span>.png<span class="hl sym">, $(</span>directories<span class="hl sym">)))</span> \
		<span class="hl sym">$(</span><span class="hl kwa">wildcard</span> <span class="hl sym">$(</span><span class="hl kwa">addsuffix</span> <span class="hl sym">/*</span>.jpg<span class="hl sym">, $(</span>directories<span class="hl sym">)))</span> \
		<span class="hl sym">$(</span><span class="hl kwa">wildcard</span> <span class="hl sym">$(</span><span class="hl kwa">addsuffix</span> <span class="hl sym">/*</span>.svg<span class="hl sym">, $(</span>directories<span class="hl sym">)))</span>
other-files <span class="hl sym">= $(</span><span class="hl kwa">wildcard</span> <span class="hl sym">$(</span><span class="hl kwa">addsuffix</span> <span class="hl sym">/*</span>.ico<span class="hl sym">, $(</span>directories<span class="hl sym">)))</span> \
		<span class="hl sym">$(</span><span class="hl kwa">wildcard</span> <span class="hl sym">$(</span><span class="hl kwa">addsuffix</span> <span class="hl sym">/*</span>.css<span class="hl sym">, $(</span>directories<span class="hl sym">)))</span>

all-xhtml <span class="hl sym">= $(</span>text-files<span class="hl sym">:%</span>.text<span class="hl sym">=%</span>.xhtml<span class="hl sym">) $(</span>html-files<span class="hl sym">:%</span>.html<span class="hl sym">=%</span>.xhtml<span class="hl sym">)</span>
all-atom <span class="hl sym">= $(</span>text-files<span class="hl sym">:%</span>.text<span class="hl sym">=%</span>.atom<span class="hl sym">) $(</span>html-files<span class="hl sym">:%</span>.html<span class="hl sym">=%</span>.atom<span class="hl sym">)</span>

<span class="hl slc"># Commands</span>
default<span class="hl sym">:</span>
	&#64;echo <span class="hl str">&quot;No default rule, try:&quot;</span>
	&#64;echo <span class="hl str">&quot;  make all       # do almost everything&quot;</span>
	&#64;echo <span class="hl str">&quot;  make site      # generate html from written files&quot;</span>
	&#64;echo <span class="hl str">&quot;  make feed      # generate Atom feed from xhtml files&quot;</span>
	&#64;echo <span class="hl str">&quot;  make update    # will connect to the FTP server and updating change.&quot;</span>
	&#64;echo <span class="hl str">&quot;  make clean     # remove generated files&quot;</span>

<span class="hl kwa">all</span><span class="hl sym">:</span> site update

site<span class="hl sym">: $(</span>all-xhtml<span class="hl sym">)</span>

feed<span class="hl sym">: $(</span>all-atom<span class="hl sym">)</span>
	&#64;echo <span class="hl str">&quot;feed is not implemented by now&quot;</span> <span class="hl sym">&gt; /</span>dev<span class="hl sym">/</span>stderr

update<span class="hl sym">: $(</span>all-xhtml<span class="hl sym">) $(</span>img-files<span class="hl sym">) $(</span>other-files<span class="hl sym">)</span>
	<span class="hl sym">$(</span>SH<span class="hl sym">)</span> .<span class="hl sym">/</span>update.sh <span class="hl sym">$</span>?
	<span class="hl sym">$(</span>TOUCH<span class="hl sym">)</span> update

.PHONY<span class="hl sym">:</span> <span class="hl kwa">clean</span>
<span class="hl kwa">clean</span><span class="hl sym">:</span>
	<span class="hl sym">$(</span>RM<span class="hl sym">) $(</span>text-files<span class="hl sym">:%</span>.text<span class="hl sym">=%</span>.html<span class="hl sym">)</span>
	<span class="hl sym">$(</span>RM<span class="hl sym">) $(</span>all-xhtml<span class="hl sym">)</span>
	<span class="hl sym">$(</span>RM<span class="hl sym">) $(</span>all-atom<span class="hl sym">)</span>
	<span class="hl sym">$(</span>RM<span class="hl sym">)</span> update

<span class="hl slc"># Generic rules</span>
<span class="hl sym">%</span>.html<span class="hl sym">: %</span>.text
	<span class="hl sym">$(</span>MARKDOWN<span class="hl sym">) $&lt; &gt; $</span>&#64;

<span class="hl sym">%</span>.xhtml<span class="hl sym">: %</span>.html templates<span class="hl sym">/</span>default.template template.awk
	<span class="hl sym">$(</span>AWK<span class="hl sym">) -</span>f template.awk <span class="hl sym">-</span>v input<span class="hl sym">=</span><span class="hl str">&quot;$&lt;&quot;</span> <span class="hl sym">-</span>v output<span class="hl sym">=</span><span class="hl str">&quot;$&#64;&quot;</span> templates<span class="hl sym">/</span>default.template

<span class="hl sym">%</span>.atom<span class="hl sym">: %</span>.html templates<span class="hl sym">/</span>atom-entry.template template.awk
	<span class="hl sym">$(</span>AWK<span class="hl sym">) -</span>f template.awk <span class="hl sym">-</span>v input<span class="hl sym">=</span><span class="hl str">&quot;$&lt;&quot;</span> <span class="hl sym">-</span>v output<span class="hl sym">=</span><span class="hl str">&quot;$&#64;&quot;</span> templates<span class="hl sym">/</span>atom-entry.template

</pre>
</body>
</html>
<!--HTML generated by highlight 2.7, http://www.andre-simon.de/-->
